### ISSUE TITLE
Rename nr-port-monitor-plugin to nr-tcp-port-monitor

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-port-monitor#1]
**Issue:** After installing the OHI, I saw errors in the agent log stating it was unable to find the "nr-tcp-port-monitor" file. 

> time="2018-09-21T21:52:00Z" level=error msg="starting data source" data prefix=integration/com.newrelic.tcp-port-monitor error="fork/exec ./bin/nr-tcp-port-monitor: no such file or directory" plugin name=expressCart

**Fix:** After renaming nr-port-monitor-plugin to nrt-tcp-port-monitor, the OHI began working.

**Comment by preddy-newrelic** [comment]
Thanks Brad for reporting the issue. I have fixed it now and created a new release(version 1.1).
