### ISSUE TITLE
An accessible port may have a status of 0.

### ISSUE THREAD

**Issue by qryuu** [newrelic/nri-port-monitor#14]
I have confirmed that I can connect to the port via Telnet.

```sh bash
[root@hostname ~]# telnet localhost 12340
Trying ::1%1...
Connected to localhost.
Escape character is '^]'.
```

However, when I check with Port Moniter, the status is displayed as 0.

```sh bash
[root@hostname ~]# /var/db/newrelic-infra/newrelic-integrations/bin/port-monitor -address localhost:12340
{"name":"com.newrelic.tcp-port-monitor","protocol_version":"3","integration_version":"2.0.0","data":[{"metrics":[{"address":"localhost:12340","event_type":"NetworkPortSample","network":"tcp","port":"12340","status":0}],"inventory":{},"events":[]}]}
[root@hostname ~]#
```

What are the possible causes?
Is there any information you need?

I'm counting on your help.
Thank you

**Comment by preddy-newrelic** [comment]
It means the call to net.Dial to that port caused an error. Change the code here -> https://github.com/newrelic/nri-port-monitor/blob/81e8d630254f4545cdbc8cdcc01339803970760c/src/port-monitor.go#L51

from 
if err == nil {
		status = 1
		conn.Close()
}
to 
if err == nil {
		status = 1
		conn.Close()
} else {
                 panic(err)
 }
to print that error
